### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by zharikovpro** [wild5r/activeadmin_hstore_editor#14]
Would be awesome. Now it has conflicts:

```
rails (~> 5.1.1) was resolved to 5.1.1, which depends on
      railties (= 5.1.1)

activeadmin_hstore_editor was resolved to 0.0.1, which depends on
      railties (< 5.0, >= 3.0)
```

**Comment by sachin-metacube** [comment]
is this gem still active?

**Comment by KapilMetacube** [comment]
Still encountering issue even after this is merged
```
    activeadmin (~> 1.1) was resolved to 1.1.0, which depends on
      railties (< 5.2, >= 4.2)

    activeadmin_hstore_editor (~> 0.0.5) was resolved to 0.0.5, which depends on
      railties (< 5.0, >= 3.0)
```

Rubygems.org is still showing different dependency versions (old ones).

**Comment by leenasn** [comment]
The same issue exists while updating to 5.1 and 5.2. Any clue on how to fix the same?

Thanks,

**Comment by KapilSachdev** [comment]
@leenasn , I have created a PR that would resolve the issue for `rails ~> 5`. Till then you can use my branch.

**Comment by wild5r** [comment]
thanx
